### ISSUE TITLE
Get all deployments does not work correctly.   Fix or deprecate

### ISSUE THREAD

**Issue by jkranes** [smart-cow/scow#3]
DeploymentsController.listDeployments() only returns workflows in the session's active memory, not all existing deployments.  However, since there is no longer a meaningful distinction between a deployment and a processDefinition object (both just have the process key), we may just want to deprecate the deployments object altogether, as it seems to add no real value.

**Comment by lewisloren** [comment]
If the results from listDeployment() are a proper subset of processDefinition, then deprecate away.

**Comment by jkranes** [comment]
Will be deprecated.  The same information content can be obtained from GET /processDefinitions.
