### ISSUE TITLE
Use GUID rather than sequential numbers for workflow item Key

### ISSUE THREAD

**Issue by jkranes** [smart-cow/scow#30]
Use GUID rather than sequential numbers for workflow item Key.  This is consitent with latest JBPM web designer output, and also has been requested by users as a way of making sure key values are globally unique rather than just unique within a single viewpoint.

**Comment by brosenberg42** [comment]
ugh. I really dislike GUIDs, you can ensure integers are unique. I would rather say look at workflow `453`, than workflow `GUID('3F2504E0-4F89-11D3-9A0C-0305E82C3301')`.

Users should be able to differentiate `/processInstances/54` and `/tasks/54`

If we had some kind of distributed database where more than one object maybe created at the same instant, maybe GUIDs would make sense

**Comment by jkranes** [comment]
Done.  Existing workflows will need to be saved to trigger replacement of numeric IDs with GUID based IDs.
