### ISSUE TITLE
Matt research open LDAP and see if there's a way to restrict access

### ISSUE THREAD

**Issue by lewisloren** [smart-cow/scow#31]
Due Jan 14th

**Comment by mhowansky** [comment]
Seems the way most people do it is by changing the user password with some function that also has an inverse function. Seems pretty straight forward even though it’s a bit strange.

**Comment by brosenberg42** [comment]
Won’t that mean that people won’t be able to log in to scout2 until the function is reversed?
-Brian

**Comment by mhowansky** [comment]
So long as they continue to use the same LDAP server – Yes.
