### ISSUE TITLE
Ensure that webapp and server run on Linux

### ISSUE THREAD

**Issue by jkranes** [smart-cow/scow#49]
Address any portability issues so that the webapp and server can be deployed on Linux.

**Comment by lewisloren** [comment]
The built .war file works on Ubuntu, did not attempt to compile the code on Ubuntu.

**Comment by lewisloren** [comment]
Verify that the whole system, including the DB, works on Ubuntu.

**Comment by brosenberg42** [comment]
Instructions at http://www.wiredwidgets.org/documentation/cow-server/ubuntu-setup
