### ISSUE TITLE
Fix the bugs in the IDEAM workflow

### ISSUE THREAD

**Issue by lewisloren** [smart-cow/scow#50]
The workflow Hoanh and Nicole are using has a few bugs.  When it starts, the first task appears twice.  When tasks are completed they don’t vanish from the screen, until the last task completed, then all of them disappeared.  I’m not sure if the problem is in the UI or the back-end, but since the service tasks are newer and less tested than the UI, I’m guessing the problem is in the back-end.  Can you please take a look?  If the problem is in the UI please let Matt know.

**Comment by brosenberg42** [comment]
I fixed the error and redeployed on Scout2. I also checked with Hoanh, we believe the issue has been resolved.
