### ISSUE TITLE
Port UI from GWT to HTML5

### ISSUE THREAD

**Issue by lewisloren** [smart-cow/scow#65]
Tasks required for moo to implement the functionality of the GWT app:
- [x] Add ability to hide history tasks
- [x] Alphabetize workflow list
- [x] Handle multiple entries for a single cell in chiclet chart
- [x] Add ability to add additional process level variables
- [x] Workflow editor
- [x] Save new workflows
- [x] Base Actions Order
- [x] Admin Page
- [x] Active workflows page legend
- [x] Simple navigation
- [x] Styling 
- [x] Delete button on workflows page

**Comment by lewisloren** [comment]
Brian has the task page done in HTML5
![taskspage](https://cloud.githubusercontent.com/assets/5748179/2699967/abf78296-c40d-11e3-99e2-1f21781675ad.PNG)

**Comment by brosenberg42** [comment]
![capture](https://cloud.githubusercontent.com/assets/5748179/2699982/e068f14a-c40d-11e3-860f-6e484b79fdaf.PNG)

**Comment by brosenberg42** [comment]
http://scout2.mitre.org:8080/moo/tasks.html
http://scout2.mitre.org:8080/moo/activeworkflows.html
http://scout2.mitre.org:8080/moo/workflows.html

**Comment by brosenberg42** [comment]
Read only tree view for workflows. http://scout2.mitre.org:8080/moo/workflowbuilder.html
![treeview](https://cloud.githubusercontent.com/assets/5748179/2767415/e48ce03a-ca37-11e3-8f3e-ba4725812cc6.PNG)

**Comment by lewisloren** [comment]
estimating completion by May 27th

**Comment by brosenberg42** [comment]
#75 is for features not in the GWT app, but we want in moo

**Comment by lewisloren** [comment]
make a release and put it on scout 3
