### ISSUE TITLE
Implement features in moo beyond what is in the GWT app.

### ISSUE THREAD

**Issue by brosenberg42** [smart-cow/scow#75]
- [ ] Save Locally
- [ ] Robust Navigation
- [ ] Partials
- [ ] Manage Workflows Treeview (folders)?
- [ ] Seperate builds without navigation (For widgetizing)
- [ ] Add Worfkflow preview onClick (Similar to what happens when you click task in tasks.html)

**Comment by brosenberg42** [comment]
Feature request can be appended to the list above

**Comment by lewisloren** [comment]
after #77
