### ISSUE TITLE
Convert moo to use angular.js instead on knockout.js

### ISSUE THREAD

**Issue by brosenberg42** [smart-cow/scow#77]
Angular.js provides a super set of the functionality provided by knockout. Angular provides a lot of functionality, but the biggest feature that will be useful for us is html partials. Partials remove duplicated html, by creating reusable chunks of html that can be used in multiple files. It is essentially a function call for html.

**Comment by lewisloren** [comment]
Make Moo match GWT, then move to Angular.js

**Comment by lewisloren** [comment]
tasks page, chiclet chart, admin page done

**Comment by lewisloren** [comment]
need to finish workflow builder and start workflow pages
