### ISSUE TITLE
Changes to variables break service tasks

### ISSUE THREAD

**Issue by brosenberg42** [smart-cow/scow#80]
After merging Jon's changes in to dev, the service calls no longer work

**Comment by brosenberg42** [comment]
Some stuff from RestServiceTaskHandler.java has been commented out. 
(_commenting them in doesn't fix it_).
See:
https://github.com/smart-cow/scow/blob/dev/cow-server/src/main/java/org/wiredwidgets/cow/server/manager/RestServiceTaskHandler.java#L83-L87
https://github.com/smart-cow/scow/blob/dev/cow-server/src/main/java/org/wiredwidgets/cow/server/manager/RestServiceTaskHandler.java#L118-L126

**Comment by jkranes** [comment]
The new variables approach now requires that inputs to a service task must be explicitly declared as inputs in the <variables> element of the Service Task.

For example:

```
  <serviceTask name="ServiceTask 1" key="_5DE9A577-EAFA-4B4F-AD04-8EEE863A9738" bypassable="false">
     <method>POST</method>
     <url>http://www.w3schools.com/webservices/tempconvert.asmx</url>
     <content>content goes here</content>
     <contentType>text/xml</contentType>
     <var>resulttemp</var>
     <variables>
                   <!-- declare any variables that will be used in the request -->
            <variable name="tempInput" />
     </variables>
     <resultSelectorXPath>//CelsiusToFahrenheitResult/text()</resultSelectorXPath>
  </serviceTask>
```
